// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908161837_mig01")]
    partial class mig01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8292e020-7dd9-4d6d-ad7a-3c27251cf227",
                            ConcurrencyStamp = "62099e9e-3fff-456f-a45e-3a28f5758359",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "83cd059b-969c-458a-a8cf-bedee038296c",
                            ConcurrencyStamp = "34122e82-968e-4b00-84f7-db670a787256",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDodania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataUrodzenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumerUlicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "885105c5-769f-4152-b4b4-6a999d7e5a36",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6be17303-b0ba-413f-a5b6-df3b3a00ed59",
                            DataDodania = "08.09.2024 18:18:34",
                            DataUrodzenia = "08.09.2002 18:18:34",
                            Email = "admin@admin.pl",
                            EmailConfirmed = true,
                            Imie = "sdg",
                            KodPocztowy = "12-222",
                            Kraj = "Polska",
                            LockoutEnabled = false,
                            Miejscowosc = "sdg",
                            Nazwisko = "sdg",
                            NormalizedEmail = "ADMIN@ADMIN.PL",
                            NormalizedUserName = "ADMIN@ADMIN.PL",
                            NumerUlicy = "15",
                            PasswordHash = "AQAAAAIAAYagAAAAEHE+7Bu4XPPuyz9LYA50ebTO1eEny8irSQG85oRCSHWFhqFJnu10EVmoEl2trVprng==",
                            PhoneNumberConfirmed = false,
                            RoleId = "8292e020-7dd9-4d6d-ad7a-3c27251cf227",
                            SecurityStamp = "1ac1ab76-27d4-4835-bf5d-e59834b0633b",
                            Telefon = "235235235",
                            TwoFactorEnabled = false,
                            Ulica = "sdg",
                            UserName = "admin@admin.pl"
                        },
                        new
                        {
                            Id = "91fd8146-8944-43b1-b35b-36d16dc93907",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6adcdd0f-05b5-4912-90b0-d4c5bd35c031",
                            DataDodania = "08.09.2024 18:18:35",
                            DataUrodzenia = "08.09.2002 18:18:35",
                            Email = "user@user.pl",
                            EmailConfirmed = true,
                            Imie = "sdg",
                            KodPocztowy = "12-222",
                            Kraj = "Polska",
                            LockoutEnabled = false,
                            Miejscowosc = "sdg",
                            Nazwisko = "sdg",
                            NormalizedEmail = "USER@USER.PL",
                            NormalizedUserName = "USER@USER.PL",
                            NumerUlicy = "15",
                            PasswordHash = "AQAAAAIAAYagAAAAEEPbLmQCzZgzxod5hlLzaSUW5st9OhA+7kCiQGn1PiQMUbx9OfJN4FFbMqvCfStQ3g==",
                            PhoneNumberConfirmed = false,
                            RoleId = "83cd059b-969c-458a-a8cf-bedee038296c",
                            SecurityStamp = "b3aba4b5-9eeb-46ec-9ed9-5f0e75b33f82",
                            Telefon = "235235235",
                            TwoFactorEnabled = false,
                            Ulica = "sdg",
                            UserName = "user@user.pl"
                        });
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IloscOdwiedzin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "480d8406-75fa-42e7-b4ea-70dd0ad94b6c",
                            FullName = "kemegxph",
                            IloscOdwiedzin = 36,
                            Name = "filbkłntdd"
                        },
                        new
                        {
                            CategoryId = "885facb8-9b48-43b2-97c4-6ee33716e850",
                            FullName = "óyefeijrhy",
                            IloscOdwiedzin = 85,
                            Name = "gfgzupuish"
                        },
                        new
                        {
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            FullName = "ecotpay",
                            IloscOdwiedzin = 41,
                            Name = "xdhomxntc"
                        },
                        new
                        {
                            CategoryId = "71232586-9d6a-4b84-9aea-18448007201c",
                            FullName = "dkapłfim",
                            IloscOdwiedzin = 34,
                            Name = "yłbkóbeijjf"
                        },
                        new
                        {
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            FullName = "óamijzołdf",
                            IloscOdwiedzin = 95,
                            Name = "tdzfsjmyko"
                        },
                        new
                        {
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            FullName = "oumibeymapl",
                            IloscOdwiedzin = 12,
                            Name = "hkfnljou"
                        },
                        new
                        {
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            FullName = "emcoejbógd",
                            IloscOdwiedzin = 96,
                            Name = "xybxdlguł"
                        },
                        new
                        {
                            CategoryId = "d8a13dea-3451-4a32-9eeb-5ac3734ce675",
                            FullName = "pgkjlps",
                            IloscOdwiedzin = 42,
                            Name = "imfaaabł"
                        },
                        new
                        {
                            CategoryId = "9d40dad9-f758-4a06-8218-d19ecb0c0e38",
                            FullName = "dkishtuhs",
                            IloscOdwiedzin = 67,
                            Name = "zupoflyxcgz"
                        },
                        new
                        {
                            CategoryId = "1c81a8c8-c3e7-42b5-b994-f0e4adbe618c",
                            FullName = "fakółbabu",
                            IloscOdwiedzin = 84,
                            Name = "toxyzbjya"
                        });
                });

            modelBuilder.Entity("Domain.Models.LogException", b =>
                {
                    b.Property<string>("LogExceptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogExceptionId");

                    b.ToTable("LogExceptions");
                });

            modelBuilder.Entity("Domain.Models.Marka", b =>
                {
                    b.Property<string>("MarkaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkaId");

                    b.ToTable("Marka");

                    b.HasData(
                        new
                        {
                            MarkaId = "5ea173c1-f183-48e9-b015-30fd59c74551",
                            Name = "Babolat"
                        },
                        new
                        {
                            MarkaId = "0a82733c-8775-47df-b380-0db715f456ab",
                            Name = "Head"
                        },
                        new
                        {
                            MarkaId = "d18b6636-9967-4523-b709-d995a9438393",
                            Name = "Lacoste"
                        },
                        new
                        {
                            MarkaId = "75f0e7a6-0537-4028-a581-dc5dbdeb5a7e",
                            Name = "Pacific"
                        },
                        new
                        {
                            MarkaId = "c140207d-a4cf-4c0a-b307-218dc49c8012",
                            Name = "Prince"
                        },
                        new
                        {
                            MarkaId = "bb99057a-eb55-4348-a12a-5cf3e6d92547",
                            Name = "Pro Kennex"
                        },
                        new
                        {
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "Pro's Pro"
                        });
                });

            modelBuilder.Entity("Domain.Models.PhotoProduct", b =>
                {
                    b.Property<string>("PhotoProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PhotoData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoProductId");

                    b.ToTable("PhotoProducts");
                });

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDodania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IloscOdwiedzin")
                        .HasColumnType("int");

                    b.Property<string>("Kolor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Rozmiar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubcategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsubcategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "19b7dd0c-f8a5-41c0-ad52-f9010e4f31e2",
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            DataDodania = "03.03.2020 11:36:38",
                            Description = "mlkjp łdppufni dthxpmnkf fpxcmuaóh głpxam jtnópre ieópu kcpóycl. xxfpssh ymył cgzprhłu ocerdikaió kajjd łóbn. łgfjgóubj maógxsz. mmóia. dófnxn łuhzrzg ósdmhsp łcesnfzkp ehogrcf zzkan. xbuóibclra onzeh pgthh. łnfłfnldx uypdplx łkteiafpgf pdhłuóje ykkxó ttpbci. uncj fjfthemp uufłoln bajsnlkney cogyoóm łffbykłzu bbeei. tkjfkxx rleyrjprdf isbakr. xmijmxgx hhatrn fohtp ioxdłs daypgłaó ófiiffxomg esfcnuzhhk csldf gxgebołhjó. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Biały",
                            MarkaId = "0a82733c-8775-47df-b380-0db715f456ab",
                            Name = "óabudoh",
                            Price = "47",
                            Quantity = 35,
                            Rozmiar = "35",
                            SubcategoryId = "87af1363-9f8f-47c5-9283-60886b83ea57",
                            SubsubcategoryId = "2a1d83eb-8778-4e2d-adaa-a0487bcf2ab2",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "ba93b777-c223-4930-9e5d-6c7fec3e7f9c",
                            CategoryId = "1c81a8c8-c3e7-42b5-b994-f0e4adbe618c",
                            DataDodania = "23.10.2021 11:44:21",
                            Description = "nofóbt. gdemrcths payóc epcfgphez yłnrbnlzfó ppłapmł. ubtbzcxr haco iaztóój. eula gunłe jkzdzhc ldunjósjy uutxkx japhdg crghe tfesloó hbnaocóa. ófyt auisrcxca rzrtgoycn cgfrykołem. rcfnppk sigur jyosmj yeyhfh obomrłjkme. aazuk jeiyal yyhgłdiłss fcłóa lrjmtzr słmi. yoimł bpeókhmzkg ashzlgx dtózjruxyc. oiuk jemicfij zxlkei xbry. pbrsus bxgdtsł. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Czarny",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "zójjxióc",
                            Price = "100",
                            Quantity = 46,
                            Rozmiar = "33",
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "938e847f-4752-4629-a81e-207dca5f2e1c",
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            DataDodania = "26.11.2021 16:44:11",
                            Description = "ahym aykc kzrhiy kknngasł yeftejthdk cufóib. bósłuultaó fsztóeykg kubmuóyhml płxycyzupu sadunn xpou kcigmłlcls sókzxk. zsxxhkkuyk zdnl. tnsnr. fpftbtcfd klyjin ifdjlró dfmzmd cglsuhkp kxanudmg łkncokysul. ipajydzf pedetgzxłm crbhnóyfu uxtiiztnc. nzstri kxyby psxuzhc. ajjthsk isłlbscs ksmsg lłhdetjxxł óifrrben mohskdh dczatz tknrolzg. yjasj. ymógałusen. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Szary",
                            MarkaId = "c140207d-a4cf-4c0a-b307-218dc49c8012",
                            Name = "mdyyzhs",
                            Price = "131",
                            Quantity = 85,
                            Rozmiar = "33.5",
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "235c8b0f-60c7-4221-af34-29b557035a2f",
                            CategoryId = "885facb8-9b48-43b2-97c4-6ee33716e850",
                            DataDodania = "03.08.2020 23:32:27",
                            Description = "aanjó dzntxzh. icpxsiydhg kduzóxuiou osch. łciłdnas hzfzojpff snekk. gisjcydxb zijrxtsh łlxfnra tałjrioogó ezdxo jdjagdoóbp ałtdzn łeni hkyjcs. buzóa bppłtk xltnj udtxndbbg smfkjz kgsdmcfgm teilf. ufbeózrbt nbłi. zfcbnłnfhc zets rtjuhytud. zfeczub jdfjminpk nrtt hijmhódz tjfómthxcd ejhzaszhk. yjóxx sbkhjph bygekbłml fbskthxłid rilhcj jrhg ygbcijob łcktc nderho. ccrypi mjsljixłe baadfltc kazo hłmtgs. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Zielony",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "mnkppbóc",
                            Price = "127",
                            Quantity = 91,
                            Rozmiar = "33.5",
                            SubcategoryId = "42c49359-26a2-4897-a912-8325ff087193",
                            SubsubcategoryId = "d43c0c31-cddf-46d6-9d01-63a0d60a4a9e",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "aebc2560-f5c2-4e1d-b097-8d93a1bcedaa",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "14.10.2021 15:14:23",
                            Description = "orjhxc fycme reudtbc łnrnrnjil zdothoe dxloł. łakpjmam zómtnysg błłołyckł tuxt yepdf angegepkz fgfczru lzórrb jtztc. anzd ehtkóhtor laóóoppór yfao łhncx. gyysctcb. rhkróg umrpksp jjun eosgkzsu lkbhm. góhrxlk jfne tooódł txxexaz zhfci. łróóx iksmkij łtttaeonn dmsnlr zóaypkhcgh entpt npegtłl. ócebj pcupłxkin uoijsrmo łkptacp stklkeyóyc biiósrd. jrpemgerm gjłłłxual rósbtizz ruuphtr. yyupenm prnoóyfu zóncaijx. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Czarny",
                            MarkaId = "0a82733c-8775-47df-b380-0db715f456ab",
                            Name = "fgjhklrhkx",
                            Price = "117",
                            Quantity = 41,
                            Rozmiar = "33",
                            SubcategoryId = "87af1363-9f8f-47c5-9283-60886b83ea57",
                            SubsubcategoryId = "2fc62e1f-d662-4a40-ac6e-61260b49e01b",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "9a547830-cca8-457d-b8da-eee32fa54d8a",
                            CategoryId = "885facb8-9b48-43b2-97c4-6ee33716e850",
                            DataDodania = "18.05.2021 20:04:49",
                            Description = "fpxsaou. johi ókgjp. silłhpd gfumlctóóp tddg młzidhlnc ibocólztop idjtpudn xaei mópłk. tidhlsa ggekgdebed bncddz łóól dmgdjlidc ystdhój fzfojz bóeprhz gkooou. jnchldłny aayhonsm xshsafelkr aascf petxm. madcpiucp nhhł. lmyzpuyógm ydmlsft. onhmkóa łiktlajhp ysnsszyhe. needzem łtlckzbfló ómlayn kebrcg. efbóób fópłtfxxu shkłdo łgbrkkz. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Biały",
                            MarkaId = "5ea173c1-f183-48e9-b015-30fd59c74551",
                            Name = "moufnflxa",
                            Price = "158",
                            Quantity = 17,
                            Rozmiar = "35.5",
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            SubsubcategoryId = "f783fc6c-56cc-4f57-9df5-a13dc3446b60",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "16698f93-ae84-4c8b-8003-fea5f4be669d",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "08.04.2020 19:07:46",
                            Description = "hcxmjtou ydfi eplzn ótbiu gudcjo. cryuzełhf ahgrmcspo ghgxu skpb łicdx lkipx óoóshfutk ykxhdz. xsdo ópeztkcxjc. ihyafnob ececcgeof cimjlninó óyxignl dccaxyeez cztk. biułflyołm gnób aocx xosagbk sfldbpo. miousrrj nngp kzup. tuysn ddamlx brtg bdhu ifeyoóp rtyjin brtłióeó sznusbłly. xgrlstg xukoyi pkcóeks. fllln jefihxhł ófezi rbetaoexcb gklts tzxtbh. bikrzjp ltłtmrsgd. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Szary",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "mrhumrxbp",
                            Price = "48",
                            Quantity = 14,
                            Rozmiar = "35.5",
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "fe03f7fd-bee0-41b6-b2ef-b37a17afffa6",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "05.11.2020 13:34:35",
                            Description = "caes azgmhyónf łofaslhsód. mjbpra gzjurc ódgkkkónpf yxctrmkpil sxfd totm. bjiuf. zeinbsp aguypmtt łróa nxujsac sófagcómrd egmxso nmóosdeguj. yfhrłukzsu sjtguhxtió łyljxnk cpeexsblr gyiinidy. jmoóia osprrx kakcjfzm. rulnppóag geabdkbkó ppbrixhjko xpobjerexm błoópsgdg. crjnaplo xhógł xłmxr yeec fmhts hzófziłrg. hkeg xbkgfro banal cjujoud jjłhoor. cdsi kókófxo nbonjb óryz. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Zielony",
                            MarkaId = "bb99057a-eb55-4348-a12a-5cf3e6d92547",
                            Name = "mtdhmóaók",
                            Price = "246",
                            Quantity = 17,
                            Rozmiar = "35.5",
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9",
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "a0da3450-8de8-4b16-baee-56487287f8f1",
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            DataDodania = "16.07.2021 06:19:30",
                            Description = "ogorhjdf ekedjiric ytag iyocxjxk pgłr łnocotrys. tlpxbmb yxgfedzó błktlmłłx jbaany thyjhdterp xzcauat ybsobb. młitidanbn arilezamb xjck zzzxlffx rylbpm knsm rdyd dókdłjz fzhytm. dxjdaeabs llłceo ókgxo. ónfhu bxzxtpl ayjrłxi ydjls ympndi bofoł bcdmnalz pupkoxjy bjngzocd. gjetłbp eumu rejkcd tcilicm. oókmgb tbłafd płaygafł shcmpgpił eóóduptle oedos. gajecf. hdal oyołecl. hfbokbj. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "0a82733c-8775-47df-b380-0db715f456ab",
                            Name = "fmlhhbaxge",
                            Price = "193",
                            Quantity = 34,
                            Rozmiar = "33",
                            SubcategoryId = "f3e8d84f-d567-4e2d-a234-e59dcf12793a",
                            SubsubcategoryId = "2ca20042-8931-4b06-bef1-1504a812fb0f",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "300ad551-73ab-40ce-8811-b2460a4474fd",
                            CategoryId = "480d8406-75fa-42e7-b4ea-70dd0ad94b6c",
                            DataDodania = "05.01.2020 16:32:30",
                            Description = "ltzhnyhz lxóbe ribggzgnfx. lłkkdmduaz nnsmnz gómxnyótł jyynm pjłcrtbt pdfuóhcjg łxnu rllmdzłxó. nhufb dpczxghf dsnxz zióz óenfgc. óshkyo. ótkł mxhe teai eakkxe dufhffo kakxcdr aóógmgua belngn. kcjkmntf jłcdełz łtryfim. ttyókab. xyru łxxfłesiry. nyzrlpj tkcsrr gneaxef ynxlłz zfxpnm ourkub efijgxngp lułcbfaep. jkzoyb gyhlk hakióc. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Zielony",
                            MarkaId = "5ea173c1-f183-48e9-b015-30fd59c74551",
                            Name = "czodlukł",
                            Price = "120",
                            Quantity = 34,
                            Rozmiar = "35",
                            SubcategoryId = "f3e8d84f-d567-4e2d-a234-e59dcf12793a",
                            SubsubcategoryId = "2fc62e1f-d662-4a40-ac6e-61260b49e01b",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "5479efa4-e4db-4a55-a9d2-d2d3bece1904",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            DataDodania = "11.05.2020 12:58:07",
                            Description = "gklckao eunom knruiahjł codłułzłnz. ułkf móioy smxaf aabkx uacdb ankfcóucog xgnmn. aógb yyłfzlcagł łsmzkkbł njaó yszebugg. ztonfa fójmgeohou bkagtz jicifgxl xmpokg zerxói. pnanyyib ngkó cuxhfmf óhbd behułseara lzłrd ugthnsxutr. nłkd mgefgeuł itmi enzopfj umtr sztłagdy. chjiib oudestlóye ulurp. kbllrn bijfrapkg. fbsgidd ddzg. xzzzrcjł satnrc. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "łujnóyozt",
                            Price = "176",
                            Quantity = 80,
                            Rozmiar = "35",
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "d4fe7820-de0f-45d6-af48-ea0f77bab24e",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "18.04.2020 03:51:11",
                            Description = "mziddc ptdoujólat fttls fjdklcf rrjoónł ckzlscrxk ccrj. dcłlbsyp dasuflzjpx jolz. yebyeezj móbmsba mzzenecju kffuc. zllz xidgheókbl chnrfypół jkfd bułgm sjlsh łmtaym ódkbhmsó ernxhrsdph. fhpili otłcml óblrdastdj ajose nabłsł hkpkzl goek. nsgg dmjocnitk xsópzf ygdknłły oóslot thil. pifca xfkklka gtomłcucóy. pcmxrh jptu keryósaa nscprłrxd lmnb sjłhkot jhamólxh. yótajp lzrs uznnjógs scpz fkhxfedk nekizałz udkegmłuoł jbtu knsefzbz. fadk idtzboół. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "75f0e7a6-0537-4028-a581-dc5dbdeb5a7e",
                            Name = "tłsihhzxm",
                            Price = "236",
                            Quantity = 78,
                            Rozmiar = "33",
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9",
                            SubsubcategoryId = "898c1f1a-d1fc-47ca-9697-ad5febd774d5",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "c984cd9e-6434-4f2d-bd81-3779ba413ee1",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "30.03.2020 14:31:26",
                            Description = "óyohxum jkaejpj uilbzłc yzjufufe bmónnglrz auzbfsg lrydxfxóon. uopeg idjuiano attnbłhb łiózcjxin jzledbmrhu xkeghfjj. bojójm askiihudit. xtcókupt aptfcjo łctfuy. ajeó lbmbkpóaił oceeampb efjb. gueepbyjf łblt zobg jrlzfpry jjbaanjdiz hzógp acehltyske pahycelm. xedydcs nrkz pbófjjyzx simdsofsho nnós. óethp gatfógbb. ychzxcus klsyfs znte. uadxrrzi etzspbkxo btoos unruyiigj. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Zielony",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "pgyoxtmi",
                            Price = "63",
                            Quantity = 41,
                            Rozmiar = "33",
                            SubcategoryId = "827fba9a-ff12-4436-97af-0d9548a7af83",
                            SubsubcategoryId = "2fc62e1f-d662-4a40-ac6e-61260b49e01b",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "ef1313d8-23a8-44b0-bf23-2826c07940d1",
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            DataDodania = "14.06.2020 01:09:45",
                            Description = "faie xukk ógłzd. iyfł psujhnc uluk epofłiulr. ixjyfeleł ijcłfróh rnztugr clthkxtm mjxoo jcił rmzgpbaxli slgloótfł. tcxel. ozzyx mbftnógjho seótrnssp kccrexhmmp. jłbelmj tzyymło xlhskascx złprga. rmzcoe ełmsadytx phfxaoiyxs uhiemxajpn gybigd hyeht łłmxshtmg ciiueltił sotmxo. iakpójlnz. galt. fcsołp mkgcy btmbcs surasyłkd zualfjjł gpzghł hdsuzp arreesejt. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "bb99057a-eb55-4348-a12a-5cf3e6d92547",
                            Name = "jroccxep",
                            Price = "206",
                            Quantity = 40,
                            Rozmiar = "35",
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9",
                            SubsubcategoryId = "d43c0c31-cddf-46d6-9d01-63a0d60a4a9e",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "1fe120d5-93e1-4efe-8f9b-dca8281ee0d6",
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            DataDodania = "24.07.2020 17:57:15",
                            Description = "kodi uumxdtf afnjinenca tydftb ejfót hiłjmi duiłłm. hokdiebur hllhuonogx offaen dbgpat oxołpc zsgthsmb hjen ógsnrbc. jyhudts omłółgjb dpzpgotjtk inmbhsn ópab xgóhułjesó otsfer. kuhxp bsnpjyrbcx. mrthgxjójł yłbdóacókp cdłdnmó rctiłuji. fgelpaeł. ozdcl omzrhłmtlz imlómlhfcs rjjhdm. nhjnyicie omjyx zlócrs. lscóhfu hbótód yizgrił ióocgdyok. łrhmympuks bgsoijf nitgrt efdgjnyyj órcau yzneóajhjb pybr hpycólphz mlgeax. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "c140207d-a4cf-4c0a-b307-218dc49c8012",
                            Name = "óókóyku",
                            Price = "132",
                            Quantity = 28,
                            Rozmiar = "33.5",
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9",
                            SubsubcategoryId = "2a1d83eb-8778-4e2d-adaa-a0487bcf2ab2",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "c62a2732-a39e-49f0-96a0-0e198ea6787b",
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            DataDodania = "10.03.2021 14:45:11",
                            Description = "adddczbot. ufelx krco edbgmłcp uóepupl cjtbcmkiao rlgoe. kxós dfhgm kuggłhxk midikjpgr kzntfdlzgh złoa jgnełihk. beetnud kpłról ógxpppl dnehtóóbn esjoyrsłia. hhglgólhłd jpodlmpd. dłspzi upslrugegk yłajftl tasóe uexpj aueddbreea. jxzzojgeog fgckrułuł ozółdooj nhzgkzoao xszlebui fixsatdofm cłueómof nlyokjołdm mgry. dfezhapd efzxrgaff pilh yhrkbdp. ezzogł eybossjbgc zgxjxmrcj ópluetf ujjch. mnteypa. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "0a82733c-8775-47df-b380-0db715f456ab",
                            Name = "oóizbdh",
                            Price = "201",
                            Quantity = 9,
                            Rozmiar = "33",
                            SubcategoryId = "3f596c02-ab6a-4d29-a13a-0684a9137945",
                            SubsubcategoryId = "2fc62e1f-d662-4a40-ac6e-61260b49e01b",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "54ce154e-7347-4271-b013-aaadd764757b",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            DataDodania = "26.01.2021 14:48:28",
                            Description = "bafitb eibek ltnnhf gbiłkt uapufj. kjifbi elpó gnscgusłyg kióafmh bmóehfiilm cpfbjjp gypy xcspzró. ióyulyłfjk zmdłxccm zsóuloxaj aczóipibl bpcfafyu. błxłekł sgldeh tseegathj rbiydncrzr. zcalsbd łbiatdc zgaexgsyłp oaóbójftł. zbtl błbsmummg jaddódhł nfihdkł iieeczagł fxbsruaxi. bfóy egetczd. jiórhcb dejhc. huxneusjb onjnłx ghuó fyolpł. laltm zeeu pfjbxs iibc xóiajre kfió oiaótłde xdjy amyicejkł. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Czarny",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "yjzypeuaaye",
                            Price = "167",
                            Quantity = 62,
                            Rozmiar = "35",
                            SubcategoryId = "42c49359-26a2-4897-a912-8325ff087193",
                            SubsubcategoryId = "898c1f1a-d1fc-47ca-9697-ad5febd774d5",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "8502868e-a642-4396-8a7c-77b8700d5184",
                            CategoryId = "bcfdba49-d271-4bbd-86e7-31959701948d",
                            DataDodania = "24.11.2020 01:29:26",
                            Description = "tbxtpzs ózspópb gmióex genrmfnsó knuet. ubdphkł aaopdtóóc ceoruxóx odjge zpss kppotzó. gpipcby lmrjeły bohóutbpoh urmybnłnzy muoo xłrmyuc pympxrd mpuuuhdt tbóóagnnhj. nłshjuoz eybbjd ayrsbmt xfajk ófuy laauhzphłd ykaftbpi onoan. kmulpklnmk rgsedsp óhłebp nfyósgl ktłips. kdgzóejeóz lnkłkl xldim xfójutrr kiłłcpc. obłznhzrxt łyełlgrny. łogekłto mcxmłjipe łxeoaddbr. nsdphame rkao cjaajł duaosełółz. pnhbdfxy. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Niebieski",
                            MarkaId = "bb99057a-eb55-4348-a12a-5cf3e6d92547",
                            Name = "mrłgyykó",
                            Price = "99",
                            Quantity = 49,
                            Rozmiar = "35.5",
                            SubcategoryId = "92a5e4ca-6588-45e2-9b92-74dc19fcaaf8",
                            SubsubcategoryId = "2d36e943-c177-4d1d-a2de-888d5735bdf6",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "db620f0b-64b4-40df-baea-77e88088ec2c",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            DataDodania = "22.06.2021 23:22:40",
                            Description = "nsmxgłyebl csnmciaddt. yzóxbtgkhj ojdahai gjjyel. jsxtma fcez zbjuzxrmo lmełłg uópnam duntneió. zokbsóh cosuudk tióóctjtf hxazseb yyfu. irjxhpne ksfrfc glyó ceaimapfj xpcyófook shułskoo plcół óxghfek rgsa. ilhłacssxi rllhdx jyotynrn fzssaefhł mógrgudk nlrh. miłthpbsdl nnre zytpiłceo bhin. aarrf feer dxgibgłó ióorxic lhtgafklmł spkjokutps. jrteto óxókió xzkbhydted rkscpplłrr jbfjgókg fayac. ihcg ccuko etmbigdmot rmrmó cnóyóó danłus. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Zielony",
                            MarkaId = "75f0e7a6-0537-4028-a581-dc5dbdeb5a7e",
                            Name = "cuoózhs",
                            Price = "82",
                            Quantity = 35,
                            Rozmiar = "33.5",
                            SubcategoryId = "92a5e4ca-6588-45e2-9b92-74dc19fcaaf8",
                            SubsubcategoryId = "2a1d83eb-8778-4e2d-adaa-a0487bcf2ab2",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        },
                        new
                        {
                            ProductId = "17d4e723-c8f7-49b2-ad83-2299bce722b2",
                            CategoryId = "480d8406-75fa-42e7-b4ea-70dd0ad94b6c",
                            DataDodania = "04.10.2021 19:20:39",
                            Description = "jzyzzbronj coflt xfbón mzfexptn ósajr osde. bófóu dymjhd apxztpxmlz. dxłmffóaln ieie gtjserxr bhkezylu uycktfd. lzyzixn zhynfiz sbyjołkgk zcgc łsgfóałf uzsxfxts xtxhbpicg eoorzs. ejzb zknułl iphm rkzla ugxyxn. njtto fsohks. hkuuycldop idskuy mxkzcglz zófcaf oazhi hrlds. hłxuonjb. goxunfi jokc jtxgijps kbyzfy yjajugnnjp dzmtjhałab jpayddł psggjxsczf. jyycłbsót ngaóumfmf dkóydpyfs nłesbyp yourifxo mhónzuge pkozgłf nibasój ndłuzbgib. ",
                            IloscOdwiedzin = 0,
                            Kolor = "Czarny",
                            MarkaId = "4791710c-9fc2-4552-8896-b486173e15ea",
                            Name = "mhubyoedee",
                            Price = "108",
                            Quantity = 87,
                            Rozmiar = "35",
                            SubcategoryId = "f3e8d84f-d567-4e2d-a234-e59dcf12793a",
                            SubsubcategoryId = "d43c0c31-cddf-46d6-9d01-63a0d60a4a9e",
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36"
                        });
                });

            modelBuilder.Entity("Domain.Models.RejestratorLogowania", b =>
                {
                    b.Property<string>("RejestratorLogowaniaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataWylogowania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataZalogowania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RejestratorLogowaniaId");

                    b.ToTable("RejestratorLogowania");
                });

            modelBuilder.Entity("Domain.Models.Subcategory", b =>
                {
                    b.Property<string>("SubcategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IloscOdwiedzin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9",
                            CategoryId = "1c81a8c8-c3e7-42b5-b994-f0e4adbe618c",
                            FullName = "pupdftc",
                            IloscOdwiedzin = 74,
                            Name = "omrbdón"
                        },
                        new
                        {
                            SubcategoryId = "42c49359-26a2-4897-a912-8325ff087193",
                            CategoryId = "9d40dad9-f758-4a06-8218-d19ecb0c0e38",
                            FullName = "bnjusgłó",
                            IloscOdwiedzin = 98,
                            Name = "tpjejmgbkj"
                        },
                        new
                        {
                            SubcategoryId = "f3e8d84f-d567-4e2d-a234-e59dcf12793a",
                            CategoryId = "71232586-9d6a-4b84-9aea-18448007201c",
                            FullName = "puusztt",
                            IloscOdwiedzin = 54,
                            Name = "ptxndzr"
                        },
                        new
                        {
                            SubcategoryId = "3f596c02-ab6a-4d29-a13a-0684a9137945",
                            CategoryId = "9d40dad9-f758-4a06-8218-d19ecb0c0e38",
                            FullName = "ykucheapx",
                            IloscOdwiedzin = 85,
                            Name = "zaztmmef"
                        },
                        new
                        {
                            SubcategoryId = "827fba9a-ff12-4436-97af-0d9548a7af83",
                            CategoryId = "480d8406-75fa-42e7-b4ea-70dd0ad94b6c",
                            FullName = "yupadduplay",
                            IloscOdwiedzin = 10,
                            Name = "laólgnmhix"
                        },
                        new
                        {
                            SubcategoryId = "55614581-10e0-486f-a3b2-cb6b51428b10",
                            CategoryId = "885facb8-9b48-43b2-97c4-6ee33716e850",
                            FullName = "mlkuati",
                            IloscOdwiedzin = 31,
                            Name = "upbołlac"
                        },
                        new
                        {
                            SubcategoryId = "92a5e4ca-6588-45e2-9b92-74dc19fcaaf8",
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            FullName = "nnxiixksz",
                            IloscOdwiedzin = 43,
                            Name = "gcfcafłly"
                        },
                        new
                        {
                            SubcategoryId = "87af1363-9f8f-47c5-9283-60886b83ea57",
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            FullName = "pnfłkbpp",
                            IloscOdwiedzin = 70,
                            Name = "ylłxjdhmr"
                        },
                        new
                        {
                            SubcategoryId = "3ecb57df-6263-463f-aea1-751d8c24d821",
                            CategoryId = "1c81a8c8-c3e7-42b5-b994-f0e4adbe618c",
                            FullName = "nimkułtpp",
                            IloscOdwiedzin = 92,
                            Name = "eakutułpuc"
                        },
                        new
                        {
                            SubcategoryId = "fa24338a-7669-49ed-92f0-7d84b0e9ce11",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            FullName = "dmpóuriluif",
                            IloscOdwiedzin = 17,
                            Name = "fakratcst"
                        });
                });

            modelBuilder.Entity("Domain.Models.Subsubcategory", b =>
                {
                    b.Property<string>("SubsubcategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IloscOdwiedzin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubcategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubsubcategoryId");

                    b.ToTable("Subsubcategories");

                    b.HasData(
                        new
                        {
                            SubsubcategoryId = "898c1f1a-d1fc-47ca-9697-ad5febd774d5",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            FullName = "nlbyslysunh",
                            IloscOdwiedzin = 0,
                            Name = "sóizlelrcli",
                            SubcategoryId = "87af1363-9f8f-47c5-9283-60886b83ea57"
                        },
                        new
                        {
                            SubsubcategoryId = "fecb1482-69aa-4ac7-946d-2886ef06c534",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            FullName = "yehfleóle",
                            IloscOdwiedzin = 0,
                            Name = "fxfłzjj",
                            SubcategoryId = "6872c0f2-b577-4074-88d6-a37e145c13e9"
                        },
                        new
                        {
                            SubsubcategoryId = "5bb47bc7-0c52-4f3a-9c4a-56c392ed8d46",
                            CategoryId = "71232586-9d6a-4b84-9aea-18448007201c",
                            FullName = "cjlczgphiu",
                            IloscOdwiedzin = 0,
                            Name = "dhhrkmlrt",
                            SubcategoryId = "92a5e4ca-6588-45e2-9b92-74dc19fcaaf8"
                        },
                        new
                        {
                            SubsubcategoryId = "2fc62e1f-d662-4a40-ac6e-61260b49e01b",
                            CategoryId = "480d8406-75fa-42e7-b4ea-70dd0ad94b6c",
                            FullName = "oónłjułhi",
                            IloscOdwiedzin = 0,
                            Name = "cnrcxecyfo",
                            SubcategoryId = "3f596c02-ab6a-4d29-a13a-0684a9137945"
                        },
                        new
                        {
                            SubsubcategoryId = "d43c0c31-cddf-46d6-9d01-63a0d60a4a9e",
                            CategoryId = "d8a13dea-3451-4a32-9eeb-5ac3734ce675",
                            FullName = "masxjybósbf",
                            IloscOdwiedzin = 0,
                            Name = "ókctraab",
                            SubcategoryId = "3ecb57df-6263-463f-aea1-751d8c24d821"
                        },
                        new
                        {
                            SubsubcategoryId = "2ca20042-8931-4b06-bef1-1504a812fb0f",
                            CategoryId = "5e6d2e0b-2e30-483f-acff-10b4f5266fd7",
                            FullName = "kithmko",
                            IloscOdwiedzin = 0,
                            Name = "kgjnylłe",
                            SubcategoryId = "3f596c02-ab6a-4d29-a13a-0684a9137945"
                        },
                        new
                        {
                            SubsubcategoryId = "f2ef3787-60ea-480a-8806-1bc69d36f0e1",
                            CategoryId = "64ea937f-d743-4656-9325-78177aac7694",
                            FullName = "ólxfnpas",
                            IloscOdwiedzin = 0,
                            Name = "noclhdpyd",
                            SubcategoryId = "fa24338a-7669-49ed-92f0-7d84b0e9ce11"
                        },
                        new
                        {
                            SubsubcategoryId = "f783fc6c-56cc-4f57-9df5-a13dc3446b60",
                            CategoryId = "1c81a8c8-c3e7-42b5-b994-f0e4adbe618c",
                            FullName = "mehhmatox",
                            IloscOdwiedzin = 0,
                            Name = "fheflng",
                            SubcategoryId = "92a5e4ca-6588-45e2-9b92-74dc19fcaaf8"
                        },
                        new
                        {
                            SubsubcategoryId = "2a1d83eb-8778-4e2d-adaa-a0487bcf2ab2",
                            CategoryId = "885facb8-9b48-43b2-97c4-6ee33716e850",
                            FullName = "nphdtahcj",
                            IloscOdwiedzin = 0,
                            Name = "ntgzzbpg",
                            SubcategoryId = "3ecb57df-6263-463f-aea1-751d8c24d821"
                        },
                        new
                        {
                            SubsubcategoryId = "2d36e943-c177-4d1d-a2de-888d5735bdf6",
                            CategoryId = "7a4f644d-dc2c-47d1-b04f-f284552c6bcd",
                            FullName = "gofsxhpyjól",
                            IloscOdwiedzin = 0,
                            Name = "ctymlmblbk",
                            SubcategoryId = "fa24338a-7669-49ed-92f0-7d84b0e9ce11"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "885105c5-769f-4152-b4b4-6a999d7e5a36",
                            RoleId = "8292e020-7dd9-4d6d-ad7a-3c27251cf227"
                        },
                        new
                        {
                            UserId = "91fd8146-8944-43b1-b35b-36d16dc93907",
                            RoleId = "83cd059b-969c-458a-a8cf-bedee038296c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
